### ISSUE TITLE
"Job title display" mismatch between peviitor.ro and siiromania.ro

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_js#43]
ENVIRONMENT: PROD
  url: https://peviitor.ro/rezultate?q=sii&country=Rom%C3%A2nia&page=1
  browser: Chrome

STEPS TO REPRODUCE:
  1) open url in browser
  2)  go to "C#Developer" and click on the "Vezi postul"
  3)  check the job title from the Sii Company

EXPECTED RESULTS:
  the job title for ''C# Developer'' should be the same as the job title for the Sii company

ACTUAL RESULTS:
  job title is different than the real one
  "C++Developer" is displayed instead of "C# Developer"

**Comment by Codetamer333** [comment]
Bug is not fixed  but it is not a scraper bug, it's SII's fault !
