### ISSUE TITLE
"Displayed number of jobs" discrepancy between peviitor.ro and siiromania.ro

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_js#44]
ENVIRONMENT: PROD
  url: https://peviitor.ro/
  browser: Chrome

STEPS TO REPRODUCE:
  1) open url in browser
  2)  type "Sii" in search bar
  3)  check the number of job listings displayed

EXPECTED RESULTS:
  The number of job listings displayed on peviitor.ro should match the number displayed on the siiromania.ro

ACTUAL RESULTS:
  The number of job listings displayed doesn't match 
  Jobs displayed on peviitor.ro are "20""  and  ''31'' on the siiromania.ro

**Comment by Codetamer333** [comment]
Bug fixed
