### ISSUE TITLE
ORTEC # Job listed on peviitor is not displayed on the company's site

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_js#46]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

    1. Open URL in browser
    2. Type "Ortec" in the search bar
    3.  Click on the "Implementation Consultant" job title
    4. Verify if the job is displayed on the company site
    
EXPECTED RESULTS:
Job listed on peviitor platform should also be accessible and consistent on the company's site

ACTUAL RESULTS:
"Implementation Cunsultant " job title does not appear on the company's official website. It appears that the page containing the job listings on the company's site may not be optimized or synchronized with the peviitor platform.

![Ortec](https://github.com/peviitor-ro/based_scraper_js/assets/135150327/05856155-27a3-4777-bec5-6c673f0e9af3)

**Comment by lalalaurentiu** [comment]
Job is no longer available
