### ISSUE TITLE
ORTEC - Job listed on peviitor does not appear on the company's site

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_js#47]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

     1.  Open URL in browser
     2.  Type "Ortec" in the search bar
     3.  Click on the "Visual Designer" job title
     4.  Verify is the job is displayed on the company's site
     
EXPECTED RESULTS:
  Job listed on the peviitor platform should  be accessible and consistent on the company's official website.

ACTUAL RESULT:
"Visual Designer" job does not appear on the company's official website. It appears that the page containing the job listings on the company's site may not be optimized or synchronized with the peviitor platform.

![Ortec](https://github.com/peviitor-ro/based_scraper_js/assets/135150327/8bf2a4d9-c0f7-4d21-8d15-8f8aaa6943b7)

**Comment by lalalaurentiu** [comment]
Job is no longer available

**Comment by AdiVanca** [comment]
After retest the job “Visual Designer” is no longer available
