### ISSUE TITLE
ORTEC- Job title discrepancy: peviitor vs Ortec website

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_js#48]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

     1.  Open URL in browser
     2.  Type "Ortec" in the search bar
     3.  Go to "Middle/ Senior System Administrator/ Infrastructure" job title and click on it
     4.  Verify if the job title listing on peviitor is the same as the company's website
     
EXPECTED RESULTS:
The job title displayed on peviitor should match the job title listed on the company's website for the same job listing

ACTUAL RESULTS:
The job title displayed on peviitor differs from the job title listed on the company's website

![Screenshot 2023-09-12 131634](https://github.com/peviitor-ro/based_scraper_js/assets/135150327/8040d2f1-246b-4247-9d7a-a73656ad4f1f)

![Screenshot 2023-09-12 131144](https://github.com/peviitor-ro/based_scraper_js/assets/135150327/84acbd4f-c3fb-4715-b54e-e090cb9d82b9)

**Comment by lalalaurentiu** [comment]
Job is no longer available

**Comment by AdiVanca** [comment]
After retest the job “Middle/ Senior System Administrator/ Infrastructure" is no longer available
