### ISSUE TITLE
ORTEC -  Mismatch in job listings count: peviitor vs. Ortec website

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_js#49]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

      1.  Open URL in browser
      2.  Type "Ortec" in the search bar
      3.  Verify the total number of job listing listed on peviitor
      4.  Go to Ortec website and click on "Careers"
      5.  Click on "VIEW ALL JOBS", go to "Find Opportunities" and select "Romania"
      6.  Click on "VIEW ALL JOBS" and note  the total number of job listings listed
      
EXPECTED RESULTS:
The number of job listings displayed on peviitor should match the number of job listings available on the Ortec website

ACTUAL RESULTS:
The number of job listings on peviitor differs from the number of job listings available on the Ortec website. The number of jobs on peviitor is five and the jobs listed on Ortec's website are ten.

**Comment by lalalaurentiu** [comment]
jobs number is the same

**Comment by AdiVanca** [comment]
After retest the jobs number are the same on peviitor.ro as the jobs number on ortec careers
