### ISSUE TITLE
ORTEC- Job listed on peviitor is not displayed on the company's site

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/based_scraper_js#50]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

    1. Open URL in browser
    2. Type "Ortec" in the search bar
    3.  Click on the "Software Support Consultant" job title
    4. Verify if the job is displayed on the company site
    
EXPECTED RESULTS:
Job listed on peviitor platform should also be accessible and consistent on the company's site

ACTUAL RESULTS:
"Software Support Consultantt " job title does not appear on the company's official website. It appears that the page containing the job listings on the company's site may not be optimized or synchronized with the peviitor platform.

![Ortec](https://github.com/peviitor-ro/based_scraper_js/assets/135150327/cf03d6ac-40a5-4873-ae5b-b76eecb7fa0b)

**Comment by lalalaurentiu** [comment]
job is present on their website


![Image](https://github.com/peviitor-ro/based_scraper_js/assets/67306273/f87cd9aa-3b51-4040-a8ab-0fdb2789218b)

**Comment by AdiVanca** [comment]
After retest the job "Software Support Consultant" is present on Ortecwebsite
