### ISSUE TITLE
NO CITY - Yazaki - Maintenance Technician

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_js#51]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "Yazaki - Maintenance Technician" and check the location - city
  4. Open the "Yazaki" website 
  5. Check the job location
 

EXPECTED RESULTS:
The location of the job is the city of Arad as on the Yazaki website

ACTUAL RESULTS:
The job does not have a location/city

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/a7741fb4-102c-46e9-b72c-337937a74402)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/d13a013b-8d1d-49a4-b357-43f6095041f5)

**Comment by lalalaurentiu** [comment]
Job is no longer available
