### ISSUE TITLE
EXPIRED JOB- Yazaki - Requirements Team Leade

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_js#52]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to  Yazaki - Requirements Team Leade
  4.  Open the "Yazaki" website 
  5. Check the validity of the "Requirements Team Leade" job

EXPECTED RESULTS:
The job "Requirements Team Leade"  is valid

ACTUAL RESULTS:
The job "Requirements Team Leade" has been filled

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/4ed22f11-9c13-4529-a4e1-706402d29066)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/49a1d937-b158-42ec-903a-85211a5668c3)

**Comment by lalalaurentiu** [comment]
Job is no longer available
