### ISSUE TITLE
NO CITY - TechTalent - Product Validation Engineer

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_js#53]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "TechTalent - Product Validation Engineer" and check the location - city
  4. Open the "TechTalent" website 
  5. Check the job location
 

EXPECTED RESULTS:
The location of the job is in Bucharest as on the TechTalent website

ACTUAL RESULTS:
The job does not have a location/city

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/847f77d1-fb2d-4231-ba48-0ef5a00543bd)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/cb7712f4-fe3a-47d0-bd99-d6109ef813e7)

**Comment by lalalaurentiu** [comment]
job is no longer available
