### ISSUE TITLE
NO CITY - TechTalent - Software QA Engineer

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/based_scraper_js#54]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "TechTalent - Software QA Engineer" and check the location - city
  4. Open the "TechTalent" website 
  5. Check the job location
 

EXPECTED RESULTS:
The job has a location/city

ACTUAL RESULTS:
The job does not have a location/city

![image](https://github.com/peviitor-ro/based_scraper_py/assets/122023703/3e68282d-edda-4a64-bf77-752f1829975e)

**Comment by lalalaurentiu** [comment]
Job is no longer Available
